import { getSession } from "@/lib/session";
import Provider from "@/providers/Mantine.provider";
import { AuthProvider } from "@/providers/context";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <AuthProvider user={user}>{children}</AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
